pragma Singleton
import QtQuick 2.15

QtObject {
	property string welcomeLinphoneLogo: "image://internal/linphone.svg"
	property string welcomeLock: "image://internal/secured.svg"
	property string welcomeOpenSource: "image://internal/open_source.svg"
	property string eyeHide: "image://internal/eye.svg"
	property string eyeShow: "image://internal/eye-slash.svg"
	property string downArrow: "image://internal/caret-down.svg"
	property string returnArrow: "image://internal/caret-left.svg"
	property string rightArrow: "image://internal/caret-right.svg"
	property string info: "image://internal/info.svg"
	property string loginImage: "image://internal/login_image.svg"
	property string belledonne: "image://internal/belledonne.svg"
	property string profile: "image://internal/user-circle.svg"
	property string manageProfile: "image://internal/user-circle-gear.svg"
	property string verif_page_image: "image://internal/verif_page_image.svg"
	property string check: "image://internal/check.svg"
	property string dialer: "image://internal/dialer.svg"
	property string dialerSelected: "image://internal/dialer-selected.svg"
	property string chiffrement: "image://internal/chiffrement.svg"
	property string interoperable: "image://internal/interoperable.svg"
	property string phone: "image://internal/phone.svg"
	property string phoneSelected: "image://internal/phone-selected.svg"
	property string newCall: "image://internal/phone-plus.svg"
	property string endCall: "image://internal/phone-disconnect.svg"
	property string adressBook: "image://internal/address-book.svg"
	property string adressBookSelected: "image://internal/address-book-selected.svg"
	property string chatTeardropText: "image://internal/chat-teardrop-text.svg"
	property string chatTeardropTextSelected: "image://internal/chat-teardrop-text-selected.svg"
	property string usersThree: "image://internal/users-three.svg"
	property string usersThreeSelected: "image://internal/users-three-selected.svg"
	property string noItemImage: "image://internal/noItemImage.svg"
	property string verticalDots: "image://internal/dots-three-vertical.svg"
	property string plusCircle: "image://internal/plus-circle.svg"
	property string micro: "image://internal/microphone-stage.svg"
	property string groupCall: "image://internal/group-call.svg"
	property string magnifier: "image://internal/magnifying-glass.svg"
	property string backspaceFill: "image://internal/backspace-fill.svg"
	property string closeX: "image://internal/x.svg"
	property string incomingCall: "image://internal/incoming_call.svg"
	property string incomingCallMissed: "image://internal/incoming_call_missed.svg"
	property string incomingCallRejected: "image://internal/incoming_call_rejected.svg"
	property string outgoingCall: "image://internal/outgoing_call.svg"
	property string outgoingCallMissed: "image://internal/outgoing_call_missed.svg"
	property string outgoingCallRejected: "image://internal/outgoing_call_rejected.svg"
}
