AUT=Linphone
LANGUAGE=JavaScript
OBJECTMAP=shared/scripts/names.js
TEST_CASES=tst_Startup tst_Login tst_TwoInstances tst_ChatBasic tst_ChatConference tst_Call tst_SettingThirdPartyAccount tst_SettingCreateAccount tst_SettingChatFeature tst_SettingMeetingsFeature tst_SettingHideSettings tst_SettingHideAccountSettings tst_SettingDisableCallRecordings tst_SettingHideSipAddresses tst_SettingDisableCallForward tst_SettingDisableBroadcastFeature tst_SettingDisableCommandLine
VERSION=3
WRAPPERS=Qt
