AUT=Linphone
LANGUAGE=JavaScript
OBJECTMAP=shared/scripts/names.js
TEST_CASES=tst_Startup tst_Login tst_TwoInstances tst_ChatBasic tst_ChatConference tst_Call tst_SettingsAllShown tst_SettingsAllHidden tst_BDD_Redial
VERSION=3
WRAPPERS=Qt
