#################################################
# Ccache
#################################################

.linux-ccache:

  cache:
    key: $CI_JOB_NAME
    paths:
      - ccache/

  before_script:
    - mkdir -p ccache
    - echo "max_size = $CCACHE_SIZE" > ccache/ccache.conf
    - export CCACHE_BASEDIR=${PWD}
    - export CCACHE_DIR=${PWD}/ccache
    - ccache -s

  after_script:
    - export CCACHE_DIR=${PWD}/ccache
    - ccache -s

#################################################
# Job
#################################################

.job-linux-desktop:

  stage: build

  extends: .linux-ccache

  script:
    - export CC=$CC
    - export CXX=$CXX
    - ./prepare.py -G "$CMAKE_GENERATOR" -cc $DEFAULT_LINUX_CMAKE_OPTIONS $CMAKE_OPTIONS
    - cmake --build WORK/desktop/cmake -- $ADDITIONAL_BUILD_OPTIONS

#################################################
# RPM
#################################################

.job-linux-rpm:

  stage: package

  script:
    - sudo rpm -i --replacepkgs /linphone-qt-*
    - ./prepare.py desktop-rpm $DEFAULT_CMAKE_OPTIONS $CMAKE_OPTIONS
    - make

  artifacts:
    paths:
      - WORK/desktop-rpm/rpmbuild/RPMS/x86_64/*.rpm
    when: always
    expire_in: 1 week

#################################################
# Schedule
#################################################

.scheduled-job-linux-desktop:

  extends: .job-linux-desktop
  only:
    - schedules