set(APPLICATION_DESCRIPTION "Você com seu novo mundo!")
set(APPLICATION_ID "br.net.sincroniza.sincronizaphone")
set(APPLICATION_NAME SincronizaPhone)
set(APPLICATION_URL "https://www.sincroniza.net.br")
set(APPLICATION_VENDOR "Sincroniza Digital")
set(APPLICATION_LICENCE "GNU General Public License V3")
set(APPLICATION_LICENCE_URL "https://www.gnu.org/licenses/gpl-3.0.html")
set(APPLICATION_START_LICENCE "2010")
set(APPLICATION_SEMVER ${LINPHONEAPP_VERSION})

set(EXECUTABLE_NAME sincronizaphone)
