#!/usr/bin/env bash

# See: http://wiki.qt.io/Building_Qt_5_from_Git
# See: http://doc.qt.io/qt-5/configure-options.html

REPO_URL='https://gitlab.linphone.org/BC/public/external/qt5.git'
QT_VERSION='5.12.5'

RPM_NAME=linphone-qt-${QT_VERSION}

REPO_FOLDER=linphone-qt
RPM_FOLDER=rpm-${RPM_NAME}

# ==============================================================================
RED='\e[1;31m'
NC='\e[0m'

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${SCRIPT_DIR}/.."

# ==============================================================================

if [ ! -d "${REPO_FOLDER}/.git" ]; then
  
  function convert_to_integer {
   echo "$@" | awk -F "." '{ printf("%03d%03d%03d\n", $1,$2,$3); }';
  }
  #parsing git version command to get only version numbers
  GIT_VERSION=$(git --version | sed 's|.*version \([0-9\.]*\).*|\1|')
  PARALLEL_FETCH='';
  if [ "$(convert_to_integer ${GIT_VERSION})" -gt "2.8.0" ];then
    PARALLEL_FETCH='-j12'
  fi

  git clone "${REPO_URL}" "${REPO_FOLDER}" "${PARALLEL_FETCH}"
fi
cd "${REPO_FOLDER}"
while test $# -gt 0
do
  case "$1" in
    --clean)
      echo "Clean..."
      git submodule foreach 'git clean -dfx'
      ;;
    --*) echo "Invalid option: $1"
      ;;
  esac
  shift
done

git checkout "${QT_VERSION}"
if [[ $? != 0 ]] ; then
  printf "${RED}Unable to checkout ${QT_VERSION}.${NC}\n"
  exit 1
fi

./init-repository --module-subset=default,\
-qtandroidextras,\
-qtcharts,\
-qtdoc,\
-qtlocation,\
-qtmacextras,\
-qtnetworkauth,\
-qtpurchasing,\
-qtremoteobjects,\
-qtrepotools,\
-qtscript,\
-qtscxml,\
-qtsensors,\
-qtspeech,\
-qtwebchannel,\
-qtwebengine,\
-qtwebglplugin,\
-qtwebsockets,\
-qtwebview,\
-qtwinextras,\
-qtx11extras,\
-qtxmlpatterns \
-f

cd ..

mkdir -p ${RPM_FOLDER}/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
#use pigz to parallelize compression
tar --transform "s/^${REPO_FOLDER}/${RPM_NAME}/" -cf | pigz -p 12 ${RPM_FOLDER}/rpmbuild/SOURCES/${RPM_NAME}.tar.gz ${REPO_FOLDER}/
#tar --transform "s/^${REPO_FOLDER}/" -czvf ${RPM_FOLDER}/rpmbuild/SOURCES/${RPM_NAME}.tar.gz ${REPO_FOLDER}/

rpmbuild -bb --define "_topdir $PWD/${RPM_FOLDER}/rpmbuild" build/rpm/qt5.spec
